name: ROS 2 CI
on:
  pull_request:
    paths-ignore: ['**.md', '**.rst', '.gitignore']
    branches: [main]
    types: [opened, reopened, synchronize]
jobs:
  build_and_test:
    runs-on: ubuntu-24.04
    steps:
    - uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: rolling
    - uses: ros-tooling/action-ros-ci@v0.3
      with:
        target-ros2-distro: rolling
